version: '3.9'

services:

  # db:
  #   image: nouchka/sqlite3:latest
  #   container_name: db-sqlite3

  #   environment:
  #     - SQLITE3_DB=db.sqlite3
  #   volumes:
  #     - ./data/db:/root/db
      
  backend: 
    build:   
      context: ./backend
      dockerfile: Dockerfile
  
    image: django-app:latest

    # environment:
    #   - SQLITE3_DB=db.sqlite3

    ports:
      - '8000:8000'
    # volumes:
    #  - ./backend/backend:/app/backend
    # depends_on:
    #   - db
      


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react-app:latest
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
