apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      name: react-deployment
      labels:
        app: react
    spec:
      containers:
      - name: react-app
        image: rajesh93/react-app:latest
        ports:
        - containerPort: 3000



---

apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: 31110


